# Complementing a Strand of DNA
## http://rosalind.info/problems/revc/

dna = "TCCGCTCAAATTGACACGACGGACCTACAGCACACGGCTATACCCAATGGCAACTAAGGCGACTTCCAAGAGGCATTGCATGCAGTGCGTAAAAGACTCAACCAGCGTTTGGTAAGTTTATCGCCTGGGAGATTTGAGCAGAACTTATGGGAAGAAGAGGATCTCAGAGCATGAGATTTGCTTCGTGTCTATGAATAATAATGAGGCAATCAATTTCTCTCCCTGTCAGTACAAGATTCGCGCGACCATTGGTCAAATCCTGATAGTAATGGGCCACTTCTTATGGCCTGATGTAAAAAAATAAACGATTTTCCTTCGGGTAGCAGCAAACGGGACGTGATACGATATCACTTGCAGATGGTGGGGCTGCGCGGAGTGGGGCGTCTTGCGGCGGTAGTACACCGGGATGTATGCCAGTTTTCGAACACCCGAATACGAGGGTGCAGACACTTAAGCCCGCAAATGTGTACGAATCCCCAGGAGTTTGATGCAACTTTTTCACTACAACCCTGTTCGGAGATGATGTGCCCTATTGGCAATAAAGTGAAATGCGCTGCCCAACGTCCAAGTTTTTCCTATAGGAGGAGAGTATATTAACGCCTGATTTTTGTTCCGTAGCAACACTTGCCGCCTAGGCTGTTTGGGGGCTTGCCTAGTACACGTACGAACGCCGCTGTCGGTATTAATCGCCTCTGCCCGCAATCCCCAGTTGAACCGTAACTCACGGCACAAGACATAGCACTGCGGATACGATCGGCCCCGGCGTCCAATCTGTGGTACGCCGTGTGGAGCCTGGTTGTCCTCCATACTGTAAGGCCAATCGCCAGCTTAACTGAGGCGCCACAGGCAAACATGTA"

dna_r = dna[::-1]
dna_rc = []

for i in dna_r:
    if i == "T":
        dna_rc.append("A")
    elif i == "A":
        dna_rc.append("T")
    elif i == "C":
        dna_rc.append("G")
    elif i == "G":
        dna_rc.append("C")

print("".join(dna_rc))