# Finding a Motif in DNA
## http://rosalind.info/problems/subs/

s = 'AACATTAGGGTAAGTTTAGGGTCCGTTAGGGTTTAGGGTCCTTAGGGTACCCCTTAGGGTGTTAGGGTTTAGGGTTTAGGGTTTGTTAGGGTCCCATTAGGGTTCGCAAGTACTTAGGGTCACTTAGGGTGCCTGTGTTAGGGTTTAGGGTCCGGGCGTTAGGGTGTTAGGGTTTAGGGTACTATTAGGGTCTCATTAGGGTGTTTAGGGTGGGGGTTAGGGTGCACCAGATGCTTAGGGTTTAGGGTTAAATAATTAGGGTTACTTAGGGTTCTGTGGACATTAGGGTAATGAATTAGGGTCAATTATTTTAGGGTGTTAGGGTTTAGGGTCTTAGGGTCCGTTAGGGTCATTTAGGGTGTTAGGGTTTAGTTAGGGTTTAGGGTCATTTAGGGTATTCTCCTCCGAAATTAGGGTTTAGGGTTTAGGGTTTAGGGTTGTTAGGGTTTAGGGTTTAGGGTCTCCATTAGGGTGGCCCGTTAGGGTGTCCGTTAGGGTTTAGGGTTTAGGGTGGACTTAGGGTCTTAGGGTTAGCGCCAGAATACATTAGGGTAGATTTAGGGTTTAGGGTTGTTAGGGTTTAGGGTGCTTAGGGTTTTAGGGTTGTATATCTTTAGGGTCCCAATTAGGGTTTAGGGTATTAGGGTCTTAGGGTGTTAGGGTGTTTAGGGTGTGTTAGGGTTTAGGGTGTTAGGGTGTAGTGGGATGTCGGTTAGGGTTTTAGGGTCGAGTTTTGTGAACATTCTTAGGGTTTAGGGTTTAGGGTATTAGGGTCAACTTTAGGGTTTTTAGGGT'
t = 'TTAGGGTTT'
positions = []
for i in list(range(len(s))):
    if s[i:i+len(t)] == t[0:len(t)]:
        positions.append(str(i+1))
    else:
        continue

print(" ".join(positions))